BEGIN;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP VIEW IF EXISTS customer_orders_unified;
DROP TABLE IF EXISTS audit_log, admin_notifications, site_notifications, smart_notification_events,
  chatbot_messages, chatbot_sessions, smart_report_snapshots, complaint_messages, complaints,
  booking_items, bookings, store_order_items, store_orders, store_products, menu_items,
  time_slots, rooms, site_users, admins, business_hours, system_settings CASCADE;

CREATE TABLE admins (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(50) NOT NULL UNIQUE,
  password varchar(255) NOT NULL,
  full_name varchar(100) NOT NULL,
  role varchar(20) NOT NULL DEFAULT 'employee',
  phone varchar(20),
  email varchar(100),
  status varchar(20) NOT NULL DEFAULT 'Active',
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rooms (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_name varchar(100) NOT NULL,
  room_type varchar(50) NOT NULL,
  price_per_hour numeric(10,2) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'Available',
  services text,
  description text,
  image_path varchar(255),
  image_uploaded_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE site_users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name varchar(120) NOT NULL,
  email varchar(150) NOT NULL UNIQUE,
  phone varchar(20),
  profile_image varchar(255),
  password_reset_token varchar(128),
  password_reset_expires_at timestamptz,
  password varchar(255) NOT NULL,
  role varchar(20) NOT NULL DEFAULT 'user',
  loyalty_points integer NOT NULL DEFAULT 0,
  status varchar(20) NOT NULL DEFAULT 'Active',
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_site_users_role_status ON site_users(role, status);
CREATE INDEX idx_site_users_password_reset_token ON site_users(password_reset_token);

CREATE TABLE business_hours (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_of_week varchar(12) NOT NULL UNIQUE,
  is_open boolean NOT NULL DEFAULT true,
  opening_time time NOT NULL DEFAULT '09:00:00',
  closing_time time NOT NULL DEFAULT '23:59:00',
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (day_of_week IN ('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'))
);

CREATE TABLE menu_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_name varchar(100) NOT NULL,
  item_category varchar(50) NOT NULL,
  item_price numeric(10,2) NOT NULL,
  item_description text,
  is_available boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE store_products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_name varchar(150) NOT NULL,
  category varchar(100) NOT NULL,
  price numeric(10,2) NOT NULL,
  description text,
  image_path varchar(255),
  stock_quantity integer NOT NULL DEFAULT 0,
  status varchar(20) NOT NULL DEFAULT 'Active',
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_store_products_status_category ON store_products(status, category);

CREATE TABLE system_settings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key varchar(100) NOT NULL UNIQUE,
  setting_value text NOT NULL,
  setting_type varchar(20) NOT NULL DEFAULT 'string',
  description text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE time_slots (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id integer REFERENCES rooms(id) ON DELETE CASCADE,
  slot_time time NOT NULL,
  slot_label varchar(20) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  UNIQUE (room_id, slot_time)
);
CREATE INDEX idx_time_slots_active_time ON time_slots(is_active, slot_time);

CREATE TABLE bookings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_code varchar(40) UNIQUE,
  customer_name varchar(100) NOT NULL,
  phone varchar(20) NOT NULL,
  email varchar(150),
  customer_session_token varchar(64),
  ticket_token varchar(255) UNIQUE,
  user_id integer REFERENCES site_users(id) ON DELETE SET NULL,
  room_id integer NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  booking_date date NOT NULL,
  start_time time NOT NULL,
  hours integer NOT NULL,
  end_time time GENERATED ALWAYS AS (start_time + (hours * interval '1 hour')) STORED,
  total_price numeric(10,2) NOT NULL,
  additional_items_total numeric(10,2) DEFAULT 0.00,
  final_total numeric(10,2) GENERATED ALWAYS AS (total_price + COALESCE(additional_items_total, 0)) STORED,
  loyalty_points_earned integer NOT NULL DEFAULT 0,
  loyalty_points_redeemed integer NOT NULL DEFAULT 0,
  loyalty_discount numeric(10,2) NOT NULL DEFAULT 0.00,
  status varchar(20) NOT NULL DEFAULT 'Pending',
  payment_status varchar(20) DEFAULT 'Unpaid',
  payment_method varchar(20),
  paid_amount numeric(10,2) DEFAULT 0.00,
  notes text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_customer_session_token ON bookings(customer_session_token);
CREATE INDEX idx_booking_user_id ON bookings(user_id);
CREATE INDEX idx_booking_datetime ON bookings(room_id, booking_date, start_time, end_time);

CREATE TABLE booking_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id integer NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
  menu_item_id integer NOT NULL REFERENCES menu_items(id) ON DELETE CASCADE,
  quantity integer NOT NULL DEFAULT 1,
  item_price numeric(10,2) NOT NULL,
  item_total numeric(10,2) GENERATED ALWAYS AS (quantity * item_price) STORED,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_booking_items_booking ON booking_items(booking_id);
CREATE INDEX idx_booking_items_menu_item ON booking_items(menu_item_id);

CREATE TABLE store_orders (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_code varchar(40) NOT NULL UNIQUE,
  user_id integer NOT NULL REFERENCES site_users(id) ON DELETE CASCADE,
  customer_name varchar(120) NOT NULL,
  phone varchar(20),
  email varchar(150),
  subtotal numeric(10,2) NOT NULL DEFAULT 0.00,
  loyalty_points_redeemed integer NOT NULL DEFAULT 0,
  loyalty_discount numeric(10,2) NOT NULL DEFAULT 0.00,
  total_amount numeric(10,2) NOT NULL DEFAULT 0.00,
  loyalty_points_earned integer NOT NULL DEFAULT 0,
  payment_status varchar(20) NOT NULL DEFAULT 'Unpaid',
  payment_method varchar(20),
  paid_amount numeric(10,2) NOT NULL DEFAULT 0.00,
  status varchar(20) NOT NULL DEFAULT 'Pending',
  stock_deducted boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_store_orders_user_created ON store_orders(user_id, created_at);
CREATE INDEX idx_store_orders_status_payment ON store_orders(status, payment_status);

CREATE TABLE store_order_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id integer NOT NULL REFERENCES store_orders(id) ON DELETE CASCADE,
  product_id integer REFERENCES store_products(id) ON DELETE SET NULL,
  product_name varchar(150) NOT NULL,
  category varchar(100),
  quantity integer NOT NULL DEFAULT 1,
  item_price numeric(10,2) NOT NULL,
  item_total numeric(10,2) GENERATED ALWAYS AS (quantity * item_price) STORED,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_store_order_items_order ON store_order_items(order_id);
CREATE INDEX idx_store_order_items_product ON store_order_items(product_id);

CREATE TABLE complaints (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_code varchar(40) UNIQUE,
  user_id integer REFERENCES site_users(id) ON DELETE SET NULL,
  customer_session_token varchar(64),
  customer_name varchar(100) NOT NULL,
  customer_email varchar(150),
  phone varchar(20),
  message text NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'Open',
  admin_reply text,
  replied_by_admin_id integer REFERENCES admins(id) ON DELETE SET NULL,
  replied_at timestamptz,
  closed_for_customer_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_complaints_code ON complaints(complaint_code);
CREATE INDEX idx_complaints_session_created ON complaints(customer_session_token, created_at);
CREATE INDEX idx_complaints_user_created ON complaints(user_id, created_at);

CREATE TABLE complaint_messages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_id integer NOT NULL REFERENCES complaints(id) ON DELETE CASCADE,
  sender_type varchar(20) NOT NULL,
  sender_user_id integer REFERENCES site_users(id) ON DELETE SET NULL,
  sender_admin_id integer REFERENCES admins(id) ON DELETE SET NULL,
  message_text text NOT NULL,
  emailed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_complaint_messages_complaint_created ON complaint_messages(complaint_id, created_at);
CREATE INDEX idx_complaint_messages_sender ON complaint_messages(sender_type, created_at);

CREATE TABLE admin_notifications (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_type varchar(50) NOT NULL,
  title varchar(150) NOT NULL,
  message text NOT NULL,
  related_table varchar(50),
  related_id integer,
  action_url varchar(255),
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_notification_read_created ON admin_notifications(is_read, created_at);
CREATE INDEX idx_notification_related ON admin_notifications(related_table, related_id);

CREATE TABLE site_notifications (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES site_users(id) ON DELETE CASCADE,
  notification_type varchar(50) NOT NULL,
  title varchar(150) NOT NULL,
  message text NOT NULL,
  action_url varchar(255),
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_site_notifications_user_read ON site_notifications(user_id, is_read, created_at);
CREATE INDEX idx_site_notifications_user_created ON site_notifications(user_id, created_at);

CREATE TABLE smart_notification_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key varchar(160) NOT NULL UNIQUE,
  audience_type varchar(20) NOT NULL,
  audience_id integer,
  notification_table varchar(40),
  notification_id integer,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_smart_notification_audience ON smart_notification_events(audience_type, audience_id, created_at);

CREATE TABLE chatbot_sessions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES site_users(id) ON DELETE SET NULL,
  session_token varchar(64) NOT NULL,
  language varchar(5) NOT NULL DEFAULT 'en',
  page_url varchar(255),
  status varchar(20) NOT NULL DEFAULT 'Open',
  closed_for_user boolean NOT NULL DEFAULT false,
  last_user_message_at timestamptz,
  last_admin_message_at timestamptz,
  closed_at timestamptz,
  started_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_chatbot_sessions_status ON chatbot_sessions(status, closed_for_user, updated_at);
CREATE INDEX idx_chatbot_sessions_user_started ON chatbot_sessions(user_id, started_at);
CREATE INDEX idx_chatbot_sessions_token ON chatbot_sessions(session_token);

CREATE TABLE chatbot_messages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id integer NOT NULL REFERENCES chatbot_sessions(id) ON DELETE CASCADE,
  sender varchar(20) NOT NULL,
  message_text text NOT NULL,
  intent varchar(50),
  response_payload text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_chatbot_messages_session_created ON chatbot_messages(session_id, created_at);
CREATE INDEX idx_chatbot_messages_intent ON chatbot_messages(intent);

CREATE TABLE smart_report_snapshots (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_type varchar(50) NOT NULL,
  report_title varchar(150) NOT NULL,
  metric_value varchar(80),
  report_payload text,
  created_by_admin_id integer REFERENCES admins(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_smart_report_type_created ON smart_report_snapshots(report_type, created_at);

CREATE TABLE audit_log (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id integer REFERENCES admins(id) ON DELETE SET NULL,
  action varchar(50) NOT NULL,
  table_name varchar(50) NOT NULL,
  record_id integer,
  old_values text,
  new_values text,
  ip_address varchar(45),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_admin_created ON audit_log(admin_id, created_at);

CREATE VIEW customer_orders_unified AS
SELECT
  'booking'::text AS record_type,
  b.id AS record_id,
  COALESCE(b.booking_code, 'FG-' || LPAD(b.id::text, 6, '0')) AS record_code,
  b.user_id,
  b.customer_name,
  b.phone,
  b.email,
  r.room_name AS item_label,
  b.status,
  b.payment_status,
  b.payment_method,
  b.final_total AS total_amount,
  b.paid_amount,
  b.loyalty_points_earned,
  b.loyalty_points_redeemed,
  b.loyalty_discount,
  b.created_at,
  b.updated_at,
  '/my-bookings'::text AS action_url
FROM bookings b
LEFT JOIN rooms r ON r.id = b.room_id
UNION ALL
SELECT
  'store_order'::text AS record_type,
  so.id AS record_id,
  so.order_code AS record_code,
  so.user_id,
  so.customer_name,
  so.phone,
  so.email,
  'Store order'::text AS item_label,
  so.status,
  so.payment_status,
  so.payment_method,
  so.total_amount,
  so.paid_amount,
  so.loyalty_points_earned,
  so.loyalty_points_redeemed,
  so.loyalty_discount,
  so.created_at,
  so.updated_at,
  '/my-bookings'::text AS action_url
FROM store_orders so;

DO $$
DECLARE table_record record;
BEGIN
  FOR table_record IN
    SELECT c.table_name
    FROM information_schema.columns c
    JOIN information_schema.tables t
      ON t.table_name = c.table_name
     AND t.table_schema = c.table_schema
    WHERE c.table_schema = 'public'
      AND c.column_name = 'updated_at'
      AND t.table_type = 'BASE TABLE'
  LOOP
    EXECUTE format(
      'CREATE TRIGGER %I_set_updated_at
       BEFORE UPDATE ON %I
       FOR EACH ROW
       EXECUTE FUNCTION set_updated_at()',
      table_record.table_name,
      table_record.table_name
    );
  END LOOP;
  -- FOR table_record IN
  --   SELECT table_name
  --   FROM information_schema.columns
  --   WHERE table_schema = 'public' AND column_name = 'updated_at'
  -- LOOP
  --   EXECUTE format('CREATE TRIGGER %I_set_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()', table_record.table_name, table_record.table_name);
  -- END LOOP;
END $$;

COMMIT;
